#!/bin/sh

echo "Xft.dpi: 200" | xrdb -merge

### BSPWM ###
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# bspwm border settings
bspc config border_width                6
bspc config window_gap                  -6
bspc config top_padding                 74
