#! /bin/sh

######################
###### AUTOSTART #####
######################

# Run a custom script depending on the detected "autorandr" setup
DETECTED_MONITOR=$(autorandr | awk '/current/ {print $1}')
$HOME/.config/autorandr/$DETECTED_MONITOR/postswitch &
$HOME/.config/autorandr/postswitch.d/programs_autorestart &

# Cursor shape
xsetroot -cursor_name left_ptr

# Launch schkd
pgrep -x sxhkd > /dev/null || sxhkd &

### MONITORS ###

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

######################
###### SETTINGS ######
######################

# Only outter gaps
for side in right bottom left ; do
	bspc config ${side}_padding     16
done

# Colors
bspc config normal_border_color         "#444444"
bspc config focused_border_color        "#18815f"

# Misc
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Alacritty:Popup sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_1 sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_2 sticky=on state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a com-st-microxplorer-maingui-STM32CubeMX state=floating
bspc rule -a Slack desktop='^5'
