#! /bin/sh

######################
###### AUTOSTART #####
######################

# Run a custom script depending on the detected "autorandr" setup
DETECTED_MONITOR=$(autorandr --detected)
if [ "$DETECTED_MONITOR" != "" ]; then
    $HOME/.config/autorandr/$DETECTED_MONITOR/postswitch &
fi

# Other programs to start
$HOME/.config/autorandr/postswitch.d/restart_programs.sh &

# Cursor shape
xsetroot -cursor_name left_ptr

# Launch schkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Set Window manager name to something else (gtk apps are broken otherwise)
wmname compiz

######################
###### SETTINGS ######
######################

# Only outter gaps
for side in right bottom left ; do
	bspc config ${side}_padding     10
done

# Colors
bspc config normal_border_color         "$COL_SYSTEM_BACKGROUND_ALT"
bspc config focused_border_color        "$COL_SYSTEM_PRIMARY"

# Misc
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

# Window rules
bspc rule -a Alacritty:Popup sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_1 sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_2 sticky=on state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
# All chat stuff to the last monitor
last_monitor="$(bspc query -D --names | sort -n | tail -n 1)"
bspc rule -a "Slack" desktop=${last_monitor}
bspc rule -a "Microsoft Teams - Preview" desktop=${last_monitor}
bspc rule -a "Rambox" desktop=${last_monitor}

# External rules
bspc config external_rules_command "$HOME/.config/bspwm/external_rules/fullscreen_floats.sh"
