#! /bin/sh

######################
###### AUTOSTART #####
######################

# Run a custom script depending on the detected "autorandr" setup
DETECTED_MONITOR=$(autorandr --detected)
if [ "$DETECTED_MONITOR" != "" ]; then
    $HOME/.config/autorandr/$DETECTED_MONITOR/postswitch &
else
    $HOME/.config/autorandr/fallback.sh &
fi

# Start programs
$HOME/.config/autorandr/postswitch.d/restart_programs.sh &

# Cursor shape
xsetroot -cursor_name left_ptr

# Launch schkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Set Window manager name to something else (gtk apps are broken otherwise)
wmname compiz

######################
###### SETTINGS ######
######################

# Only outter gaps
for side in right bottom left ; do
	bspc config ${side}_padding     10
done

# Colors
bspc config normal_border_color         "#444444"
bspc config focused_border_color        "#18815f"

# Misc
bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true

# Window rules
bspc rule -a Alacritty:Popup sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_1 sticky=on state=floating
bspc rule -a Alacritty:Scratchpad_2 sticky=on state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Slack desktop='^10'
bspc rule -a "Microsoft Teams - Preview" desktop ='^9'
