#!/bin/sh

# List of programs to start
# Add multiple instances of the same program next to eachother
PROGRAMS=(
    "nm-applet" \
    "blueman-applet" \
    "flameshot" \
    "slack -u" \
    )

# Colors for prettier output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

for program in "${PROGRAMS[@]}"; do

    #Take the first string from the list and it's previous value
    prev_program=$only_program
    only_program=$(echo $program | awk '{print $1;}')

    if [ "$only_program" == "$prev_program" ]; then
	echo "Skipping killing of $only_program because of multiple instances"
    else
	# Stop all processes
	killall -q $only_program >/dev/null 2>/dev/null

	# Wait until the process is killed
	echo -ne "${RED}Stopping${NC} $only_program..."
	while pgrep -x $only_program >/dev/null 2>/dev/null; do sleep 1; echo -n "."; done
	echo -e "${RED}Stopped${NC} $only_program"
    fi  

    # Start the processes again (full command)
    $program >/dev/null 2>/dev/null &
    echo -e "${GREEN}Restarted${NC} $only_program"
done
